### ISSUE TITLE
Resource Implementation: Azure DevOps Project

### ISSUE THREAD

**Issue by nmiodice** [nmiodice/terraform-azure-devops-hack#4]
# Description
As a user of Azure DevOps, I want to create new projects using Terraform

# Acceptance Criteria
 - [x] AzDO project can be created (in a pre-existing organization) via terraform
 ~~- [ ] AzDO project can be updated via terraform~~
 - [ ] AzDO project can be deleted via terraform

# Task Breakdown (feel free to change this!)
 - [x] Define data model (inputs and outputs)
 - [x] Implement resource schema
-  [x] Add resource schema validations
 - [x] Define state management strategy for Terraform state
 - [x] Implement state management strategy for Terraform State
 - [x] Implement CREATE function
 ~~- [ ] Implement UPDATE function~~
 - [ ] Implement DELETE function
 - [x] Implement READ function
-  [ ] Research operation status and timing issue on CREATE
 - [x] Unit tests
 - [ ] Integration tests
 - [ ] User acceptance testing
